/** Wardens Protocol — neobrutalist theme ported from the Stitch design
 *  (radical_structure/DESIGN.md). Colors/spacing/type match the source screens
 *  so their utility classes resolve 1:1. */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fbfaef",
        "on-background": "#1b1c16",
        surface: "#fbfaef",
        "surface-bright": "#fbfaef",
        "surface-dim": "#dbdad1",
        "surface-variant": "#e4e3d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f4ea",
        "surface-container": "#efeee4",
        "surface-container-high": "#eae8de",
        "surface-container-highest": "#e4e3d9",
        "on-surface": "#1b1c16",
        "on-surface-variant": "#47464d",
        "inverse-surface": "#30312a",
        "inverse-on-surface": "#f2f1e7",
        outline: "#78767e",
        "outline-variant": "#c8c5ce",
        primary: "#545173",
        "on-primary": "#ffffff",
        "primary-container": "#6c698d",
        "on-primary-container": "#f2edff",
        "primary-fixed": "#e3dfff",
        "primary-fixed-dim": "#c6c2eb",
        "on-primary-fixed": "#1a1837",
        "on-primary-fixed-variant": "#464365",
        "inverse-primary": "#c6c2eb",
        "surface-tint": "#5d5b7e",
        secondary: "#5e5e61",
        "on-secondary": "#ffffff",
        "secondary-container": "#e4e2e5",
        "on-secondary-container": "#646467",
        "secondary-fixed": "#e4e2e5",
        "secondary-fixed-dim": "#c8c6c9",
        "on-secondary-fixed": "#1b1b1e",
        "on-secondary-fixed-variant": "#474649",
        tertiary: "#575358",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6f6b70",
        "on-tertiary-container": "#f4eef3",
        "tertiary-fixed": "#e7e1e6",
        "tertiary-fixed-dim": "#cac5ca",
        "on-tertiary-fixed": "#1d1b1f",
        "on-tertiary-fixed-variant": "#49464a",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "#2FD98A",
        "bright-green": "#2FD98A",
        "sage-green": "#8FBC94",
        "neo-surface-light": "#D4D2D5",
        "neo-bg-light": "#FBFAEF",
        "neo-border-light": "#1B1C16",
        "neo-surface-dark": "#1D1E18",
        "neo-bg-dark": "#0B0E13",
        "neo-border-dark": "#D4D2D5",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        gutter: "24px",
        lg: "48px",
        xl: "80px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      fontFamily: {
        sans: ["Space Grotesk", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
        "body-md": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
